# Database connection data
DATABASE = ''
HOSTNAME = ''
PORTNUMB = ''
USERNAME = ''
PROTOCOL = ''
PASSWORD = ''

# Discord bot token
SECRET = ''
COMMAND_PREFIX = ''
OSU_API_KEY = ''

# Constants
DISCORD_MAX_LENGTH = 2000

# Command authorization keys
ALL_ACTION_ID = 1
RUN_COMMANDS_ID = 2
VERIFY_USERS = 3
DEBUG = 21
DELETE_USERS = 22
CREATE_CYCLES = 23
RENAME_CYCLES = 24
RESCHEDULE_CYCLES = 25
ADD_PARTICIPANTS = 26
ASSOCIATE_PARTICIPANTS = 27
